spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://127.0.0.1/blog?serverTimezone=GMT%2B8
    username: root
    password: root
    name: w-blog-api-prod
  flyway:
    clean-disabled: true